name: ex_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # HTTP Client
  dio: ^5.7.0
  
  # Routing
  go_router: ^14.6.2
  
  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.2
  
  # Functional Programming
  either_dart: ^1.0.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Authentication
  msal_auth: ^3.3.0
  
  # Vector Graphics
  flutter_svg: ^2.0.14
  
  # Secure Storage
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  
  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  
  assets:
    - .env
